TELEGRAM_BOT_TOKEN=tu_token_de_telegram_aquí

from telegram.ext import Updater, CommandHandler

# Manejador del comando /start
def start(update, context):
    update.message.reply_text('Hola, soy un bot de Telegram. ¡Bienvenido!')

def main():
    # Token de acceso del bot
    TOKEN = '6599928724:AAHnJvd_-lWXZ2d1kIDaZjOaoadHZm2wltc'

    # Crear el objeto updater y pasarle el token del bot
    updater = Updater(token=TOKEN, use_context=True)

    # Obtener el despachador para registrar manejadores
    dispatcher = updater.dispatcher

    # Registrar el manejador para el comando /start
    dispatcher.add_handler(CommandHandler("start", start))

    # Iniciar el bot
    updater.start_polling()

    # Mantener el bot funcionando hasta que se presione Ctrl + C
    updater.idle()

if __name__ == '__main__':
    main()
